### ISSUE TITLE
Ubuntu 20.04 crash on startup

### ISSUE THREAD

**Issue by solek1312** [shinyquagsire23/OpenJKDF2#52]
It builds no problem with CMake but crashes at this point after saying
"Loaded GOB file `resource/Res1hi.gob`...
Loaded GOB file `resource/Res2.gob`...
Premature 'END' found after only 787 lines in 'ui\jkstrings.uni'.  Check number in 'MSG xxx' header.":
[crash.log](https://github.com/shinyquagsire23/OpenJKDF2/files/7773491/crash.log)
Incredible project btw!

**Comment by shinyquagsire23** [comment]
Fixed f3fc0bb535cf48e6e012cdf369da539770a00be5 92d134057eb6b73e5420c63ab75e628913132fbd

**Comment by Calinou** [comment]
I'm using GCC 11.2.1 from the Fedora 34 repositories and OpenJKDF2 still crashes on startup. However, building with Clang let me run the game successfully. Should the warning in `BUILDING.md` be modified?

```
❯ gcc --version                          
gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

❯ clang --version
clang version 12.0.1 (Fedora 12.0.1-1.fc34)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by WaldekA** [comment]
I have the same issue with yesterday build (clang version 11.0.1-2), so that fix doesn't fix anything to me.

However, I've try to track this crash under gdb and guess what? Runs well :)... until crushed by another reason, but this deserve separate ticket.
