### ISSUE TITLE
MacOS version not launching using M2 device on Ventura Beta

### ISSUE THREAD

**Issue by BetaCarot** [shinyquagsire23/OpenJKDF2#97]
As the title says, I am unable to launch the latest release, and the release from a few days ago, using the current MacOS Beta. The application immediately crashes, both when opening normally and when trying to open it using Rozetta. Attached is the MacOS crash log.
[log.pdf](https://github.com/shinyquagsire23/OpenJKDF2/files/9539441/log.pdf)

**Comment by shinyquagsire23** [comment]
Should be fixed in v0.6.4? Let me know if it's resolved

**Comment by BetaCarot** [comment]
Sadly no, it was not fixed. this was the reason given by the OS. Strangely, I am unable to get a log of the error without rebooting as well, as the application crashes instantly if it's already crashed before.

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libcrypto.1.1.dylib
Referenced from: <BBCC2532-3E43-3362-83AA-0F35517AABB8> /Applications/OpenJKDF2_universal.app/Contents/MacOS/openjkdf2-64
Reason: tried: '/opt/homebrew/*/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libcrypto.1.1.dylib' (no such file), '/opt/homebrew/*/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

**Comment by shinyquagsire23** [comment]
Oh wait I forgot to merge the x86_64 and ARM64 `libcrypto.1.1.dylib`s. Should be set now, I just reuploaded over v0.6.4.

**Comment by BetaCarot** [comment]
Yeah, that one worked. Thanks for working so fast. I'll give the game a runthrough on this mac soon, and I'll make sure to post if I find anything else.
